// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: authen-grpc.proto

package api

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Register Req & Resp
type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	SurName       string                 `protobuf:"bytes,4,opt,name=SurName,proto3" json:"SurName,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=Location,proto3" json:"Location,omitempty"`
	BirthDate     string                 `protobuf:"bytes,7,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=Description,proto3" json:"Description,omitempty"`
	Website       []string               `protobuf:"bytes,9,rep,name=Website,proto3" json:"Website,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_authen_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_authen_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_authen_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterReq) GetSurName() string {
	if x != nil {
		return x.SurName
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RegisterReq) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *RegisterReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterReq) GetWebsite() []string {
	if x != nil {
		return x.Website
	}
	return nil
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successful    bool                   `protobuf:"varint,1,opt,name=Successful,proto3" json:"Successful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_authen_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_authen_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_authen_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResp) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

// Login Req & Resp
type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_authen_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_authen_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_authen_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserResp              `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	Cookie        string                 `protobuf:"bytes,3,opt,name=Cookie,proto3" json:"Cookie,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Expires       int64                  `protobuf:"varint,5,opt,name=Expires,proto3" json:"Expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_authen_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_authen_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_authen_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResp) GetUser() *UserResp {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

func (x *LoginResp) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LoginResp) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

type UserResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FullName       string                 `protobuf:"bytes,2,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Email          string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	ProfilePicture string                 `protobuf:"bytes,4,opt,name=ProfilePicture,proto3" json:"ProfilePicture,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserResp) Reset() {
	*x = UserResp{}
	mi := &file_authen_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResp) ProtoMessage() {}

func (x *UserResp) ProtoReflect() protoreflect.Message {
	mi := &file_authen_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResp.ProtoReflect.Descriptor instead.
func (*UserResp) Descriptor() ([]byte, []int) {
	return file_authen_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *UserResp) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UserResp) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResp) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

// RefreshToken Req & Resp
type RefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReq) Reset() {
	*x = RefreshTokenReq{}
	mi := &file_authen_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReq) ProtoMessage() {}

func (x *RefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_authen_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_authen_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserResp              `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	Cookie        string                 `protobuf:"bytes,3,opt,name=Cookie,proto3" json:"Cookie,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Expires       int64                  `protobuf:"varint,5,opt,name=Expires,proto3" json:"Expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResp) Reset() {
	*x = RefreshTokenResp{}
	mi := &file_authen_grpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResp) ProtoMessage() {}

func (x *RefreshTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_authen_grpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResp.ProtoReflect.Descriptor instead.
func (*RefreshTokenResp) Descriptor() ([]byte, []int) {
	return file_authen_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenResp) GetUser() *UserResp {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RefreshTokenResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshTokenResp) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

func (x *RefreshTokenResp) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RefreshTokenResp) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

var File_authen_grpc_proto protoreflect.FileDescriptor

const file_authen_grpc_proto_rawDesc = "" +
	"\n" +
	"\x11authen-grpc.proto\x12\x05proto\"\x89\x02\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05Email\x12\x1c\n" +
	"\tFirstName\x18\x03 \x01(\tR\tFirstName\x12\x18\n" +
	"\aSurName\x18\x04 \x01(\tR\aSurName\x12\x1a\n" +
	"\bPassword\x18\x05 \x01(\tR\bPassword\x12\x1a\n" +
	"\bLocation\x18\x06 \x01(\tR\bLocation\x12\x1c\n" +
	"\tBirthDate\x18\a \x01(\tR\tBirthDate\x12 \n" +
	"\vDescription\x18\b \x01(\tR\vDescription\x12\x18\n" +
	"\aWebsite\x18\t \x03(\tR\aWebsite\".\n" +
	"\fRegisterResp\x12\x1e\n" +
	"\n" +
	"Successful\x18\x01 \x01(\bR\n" +
	"Successful\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"\x8c\x01\n" +
	"\tLoginResp\x12#\n" +
	"\x04User\x18\x01 \x01(\v2\x0f.proto.UserRespR\x04User\x12\x14\n" +
	"\x05Token\x18\x02 \x01(\tR\x05Token\x12\x16\n" +
	"\x06Cookie\x18\x03 \x01(\tR\x06Cookie\x12\x12\n" +
	"\x04Type\x18\x04 \x01(\tR\x04Type\x12\x18\n" +
	"\aExpires\x18\x05 \x01(\x03R\aExpires\"t\n" +
	"\bUserResp\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bFullName\x18\x02 \x01(\tR\bFullName\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05Email\x12&\n" +
	"\x0eProfilePicture\x18\x04 \x01(\tR\x0eProfilePicture\"5\n" +
	"\x0fRefreshTokenReq\x12\"\n" +
	"\fRefreshToken\x18\x01 \x01(\tR\fRefreshToken\"\x93\x01\n" +
	"\x10RefreshTokenResp\x12#\n" +
	"\x04User\x18\x01 \x01(\v2\x0f.proto.UserRespR\x04User\x12\x14\n" +
	"\x05Token\x18\x02 \x01(\tR\x05Token\x12\x16\n" +
	"\x06Cookie\x18\x03 \x01(\tR\x06Cookie\x12\x12\n" +
	"\x04Type\x18\x04 \x01(\tR\x04Type\x12\x18\n" +
	"\aExpires\x18\x05 \x01(\x03R\aExpires2\xaf\x01\n" +
	"\vAuthService\x123\n" +
	"\bRegister\x12\x12.proto.RegisterReq\x1a\x13.proto.RegisterResp\x12*\n" +
	"\x05Login\x12\x0f.proto.LoginReq\x1a\x10.proto.LoginResp\x12?\n" +
	"\fRefreshToken\x12\x16.proto.RefreshTokenReq\x1a\x17.proto.RefreshTokenRespB>Z<github.com/billzayy/social-media/back-end/authen-service/apib\x06proto3"

var (
	file_authen_grpc_proto_rawDescOnce sync.Once
	file_authen_grpc_proto_rawDescData []byte
)

func file_authen_grpc_proto_rawDescGZIP() []byte {
	file_authen_grpc_proto_rawDescOnce.Do(func() {
		file_authen_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authen_grpc_proto_rawDesc), len(file_authen_grpc_proto_rawDesc)))
	})
	return file_authen_grpc_proto_rawDescData
}

var file_authen_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_authen_grpc_proto_goTypes = []any{
	(*RegisterReq)(nil),      // 0: proto.RegisterReq
	(*RegisterResp)(nil),     // 1: proto.RegisterResp
	(*LoginReq)(nil),         // 2: proto.LoginReq
	(*LoginResp)(nil),        // 3: proto.LoginResp
	(*UserResp)(nil),         // 4: proto.UserResp
	(*RefreshTokenReq)(nil),  // 5: proto.RefreshTokenReq
	(*RefreshTokenResp)(nil), // 6: proto.RefreshTokenResp
}
var file_authen_grpc_proto_depIdxs = []int32{
	4, // 0: proto.LoginResp.User:type_name -> proto.UserResp
	4, // 1: proto.RefreshTokenResp.User:type_name -> proto.UserResp
	0, // 2: proto.AuthService.Register:input_type -> proto.RegisterReq
	2, // 3: proto.AuthService.Login:input_type -> proto.LoginReq
	5, // 4: proto.AuthService.RefreshToken:input_type -> proto.RefreshTokenReq
	1, // 5: proto.AuthService.Register:output_type -> proto.RegisterResp
	3, // 6: proto.AuthService.Login:output_type -> proto.LoginResp
	6, // 7: proto.AuthService.RefreshToken:output_type -> proto.RefreshTokenResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_authen_grpc_proto_init() }
func file_authen_grpc_proto_init() {
	if File_authen_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authen_grpc_proto_rawDesc), len(file_authen_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authen_grpc_proto_goTypes,
		DependencyIndexes: file_authen_grpc_proto_depIdxs,
		MessageInfos:      file_authen_grpc_proto_msgTypes,
	}.Build()
	File_authen_grpc_proto = out.File
	file_authen_grpc_proto_goTypes = nil
	file_authen_grpc_proto_depIdxs = nil
}
