// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: post-grpc.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostReq) Reset() {
	*x = CreatePostReq{}
	mi := &file_post_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostReq) ProtoMessage() {}

func (x *CreatePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostReq.ProtoReflect.Descriptor instead.
func (*CreatePostReq) Descriptor() ([]byte, []int) {
	return file_post_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePostReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePostReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostReq) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreatePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResp) Reset() {
	*x = CreatePostResp{}
	mi := &file_post_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResp) ProtoMessage() {}

func (x *CreatePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResp.ProtoReflect.Descriptor instead.
func (*CreatePostResp) Descriptor() ([]byte, []int) {
	return file_post_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePostResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostList      []*PostResp            `protobuf:"bytes,1,rep,name=PostList,proto3" json:"PostList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResp) Reset() {
	*x = GetPostResp{}
	mi := &file_post_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResp) ProtoMessage() {}

func (x *GetPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResp.ProtoReflect.Descriptor instead.
func (*GetPostResp) Descriptor() ([]byte, []int) {
	return file_post_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetPostResp) GetPostList() []*PostResp {
	if x != nil {
		return x.PostList
	}
	return nil
}

type PostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Author        *Users                 `protobuf:"bytes,2,opt,name=Author,proto3" json:"Author,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	Media         []*PostMedia           `protobuf:"bytes,4,rep,name=Media,proto3" json:"Media,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Likes         int32                  `protobuf:"varint,6,opt,name=Likes,proto3" json:"Likes,omitempty"`
	Comments      int32                  `protobuf:"varint,7,opt,name=Comments,proto3" json:"Comments,omitempty"`
	Shares        int32                  `protobuf:"varint,8,opt,name=Shares,proto3" json:"Shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResp) Reset() {
	*x = PostResp{}
	mi := &file_post_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResp) ProtoMessage() {}

func (x *PostResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResp.ProtoReflect.Descriptor instead.
func (*PostResp) Descriptor() ([]byte, []int) {
	return file_post_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *PostResp) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostResp) GetAuthor() *Users {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *PostResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostResp) GetMedia() []*PostMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *PostResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PostResp) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *PostResp) GetComments() int32 {
	if x != nil {
		return x.Comments
	}
	return 0
}

func (x *PostResp) GetShares() int32 {
	if x != nil {
		return x.Shares
	}
	return 0
}

type DeletePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostReq) Reset() {
	*x = DeletePostReq{}
	mi := &file_post_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostReq) ProtoMessage() {}

func (x *DeletePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostReq.ProtoReflect.Descriptor instead.
func (*DeletePostReq) Descriptor() ([]byte, []int) {
	return file_post_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePostReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Users struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	FullName       string                 `protobuf:"bytes,2,opt,name=FullName,proto3" json:"FullName,omitempty"`
	ProfilePicture string                 `protobuf:"bytes,3,opt,name=ProfilePicture,proto3" json:"ProfilePicture,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_post_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_post_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_post_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *Users) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Users) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Users) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

type PostMedia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=Url,proto3" json:"Url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMedia) Reset() {
	*x = PostMedia{}
	mi := &file_post_grpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMedia) ProtoMessage() {}

func (x *PostMedia) ProtoReflect() protoreflect.Message {
	mi := &file_post_grpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMedia.ProtoReflect.Descriptor instead.
func (*PostMedia) Descriptor() ([]byte, []int) {
	return file_post_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *PostMedia) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostMedia) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PostMedia) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type LikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	mi := &file_post_grpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_grpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_post_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *LikeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LikeRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type CheckLikeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=Valid,proto3" json:"Valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLikeResp) Reset() {
	*x = CheckLikeResp{}
	mi := &file_post_grpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLikeResp) ProtoMessage() {}

func (x *CheckLikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_grpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLikeResp.ProtoReflect.Descriptor instead.
func (*CheckLikeResp) Descriptor() ([]byte, []int) {
	return file_post_grpc_proto_rawDescGZIP(), []int{8}
}

func (x *CheckLikeResp) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type AddCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentReq) Reset() {
	*x = AddCommentReq{}
	mi := &file_post_grpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentReq) ProtoMessage() {}

func (x *AddCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_grpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentReq.ProtoReflect.Descriptor instead.
func (*AddCommentReq) Descriptor() ([]byte, []int) {
	return file_post_grpc_proto_rawDescGZIP(), []int{9}
}

func (x *AddCommentReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddCommentReq) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *AddCommentReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type DeleteCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReq) Reset() {
	*x = DeleteCommentReq{}
	mi := &file_post_grpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReq) ProtoMessage() {}

func (x *DeleteCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_grpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReq.ProtoReflect.Descriptor instead.
func (*DeleteCommentReq) Descriptor() ([]byte, []int) {
	return file_post_grpc_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCommentReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteCommentReq) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

var File_post_grpc_proto protoreflect.FileDescriptor

const file_post_grpc_proto_rawDesc = "" +
	"\n" +
	"\x0fpost-grpc.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"_\n" +
	"\rCreatePostReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x18\n" +
	"\aContent\x18\x02 \x01(\tR\aContent\x12\x1c\n" +
	"\tCreatedAt\x18\x03 \x01(\tR\tCreatedAt\"*\n" +
	"\x0eCreatePostResp\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\":\n" +
	"\vGetPostResp\x12+\n" +
	"\bPostList\x18\x01 \x03(\v2\x0f.proto.PostRespR\bPostList\"\xf2\x01\n" +
	"\bPostResp\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\tR\x06PostId\x12$\n" +
	"\x06Author\x18\x02 \x01(\v2\f.proto.UsersR\x06Author\x12\x18\n" +
	"\aContent\x18\x03 \x01(\tR\aContent\x12&\n" +
	"\x05Media\x18\x04 \x03(\v2\x10.proto.PostMediaR\x05Media\x12\x1c\n" +
	"\tCreatedAt\x18\x05 \x01(\tR\tCreatedAt\x12\x14\n" +
	"\x05Likes\x18\x06 \x01(\x05R\x05Likes\x12\x1a\n" +
	"\bComments\x18\a \x01(\x05R\bComments\x12\x16\n" +
	"\x06Shares\x18\b \x01(\x05R\x06Shares\"\x1f\n" +
	"\rDeletePostReq\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\"c\n" +
	"\x05Users\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x1a\n" +
	"\bFullName\x18\x02 \x01(\tR\bFullName\x12&\n" +
	"\x0eProfilePicture\x18\x03 \x01(\tR\x0eProfilePicture\"I\n" +
	"\tPostMedia\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\tR\x06PostId\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\tR\x04Type\x12\x10\n" +
	"\x03Url\x18\x03 \x01(\tR\x03Url\"=\n" +
	"\vLikeRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\tR\x06PostId\"%\n" +
	"\rCheckLikeResp\x12\x14\n" +
	"\x05Valid\x18\x01 \x01(\bR\x05Valid\"Y\n" +
	"\rAddCommentReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\tR\x06PostId\x12\x18\n" +
	"\aComment\x18\x03 \x01(\tR\aComment\":\n" +
	"\x10DeleteCommentReq\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x16\n" +
	"\x06PostId\x18\x02 \x01(\tR\x06PostId2\xe1\x03\n" +
	"\vPostService\x129\n" +
	"\n" +
	"CreatePost\x12\x14.proto.CreatePostReq\x1a\x15.proto.CreatePostResp\x125\n" +
	"\aGetPost\x12\x16.google.protobuf.Empty\x1a\x12.proto.GetPostResp\x12:\n" +
	"\n" +
	"DeletePost\x12\x14.proto.DeletePostReq\x1a\x16.google.protobuf.Empty\x125\n" +
	"\tCheckLike\x12\x12.proto.LikeRequest\x1a\x14.proto.CheckLikeResp\x125\n" +
	"\aAddLike\x12\x12.proto.LikeRequest\x1a\x16.google.protobuf.Empty\x128\n" +
	"\n" +
	"RemoveLike\x12\x12.proto.LikeRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\n" +
	"AddComment\x12\x14.proto.AddCommentReq\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\rDeleteComment\x12\x17.proto.DeleteCommentReq\x1a\x16.google.protobuf.EmptyB<Z:github.com/billzayy/social-media/back-end/post-service/apib\x06proto3"

var (
	file_post_grpc_proto_rawDescOnce sync.Once
	file_post_grpc_proto_rawDescData []byte
)

func file_post_grpc_proto_rawDescGZIP() []byte {
	file_post_grpc_proto_rawDescOnce.Do(func() {
		file_post_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_grpc_proto_rawDesc), len(file_post_grpc_proto_rawDesc)))
	})
	return file_post_grpc_proto_rawDescData
}

var file_post_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_post_grpc_proto_goTypes = []any{
	(*CreatePostReq)(nil),    // 0: proto.CreatePostReq
	(*CreatePostResp)(nil),   // 1: proto.CreatePostResp
	(*GetPostResp)(nil),      // 2: proto.GetPostResp
	(*PostResp)(nil),         // 3: proto.PostResp
	(*DeletePostReq)(nil),    // 4: proto.DeletePostReq
	(*Users)(nil),            // 5: proto.Users
	(*PostMedia)(nil),        // 6: proto.PostMedia
	(*LikeRequest)(nil),      // 7: proto.LikeRequest
	(*CheckLikeResp)(nil),    // 8: proto.CheckLikeResp
	(*AddCommentReq)(nil),    // 9: proto.AddCommentReq
	(*DeleteCommentReq)(nil), // 10: proto.DeleteCommentReq
	(*emptypb.Empty)(nil),    // 11: google.protobuf.Empty
}
var file_post_grpc_proto_depIdxs = []int32{
	3,  // 0: proto.GetPostResp.PostList:type_name -> proto.PostResp
	5,  // 1: proto.PostResp.Author:type_name -> proto.Users
	6,  // 2: proto.PostResp.Media:type_name -> proto.PostMedia
	0,  // 3: proto.PostService.CreatePost:input_type -> proto.CreatePostReq
	11, // 4: proto.PostService.GetPost:input_type -> google.protobuf.Empty
	4,  // 5: proto.PostService.DeletePost:input_type -> proto.DeletePostReq
	7,  // 6: proto.PostService.CheckLike:input_type -> proto.LikeRequest
	7,  // 7: proto.PostService.AddLike:input_type -> proto.LikeRequest
	7,  // 8: proto.PostService.RemoveLike:input_type -> proto.LikeRequest
	9,  // 9: proto.PostService.AddComment:input_type -> proto.AddCommentReq
	10, // 10: proto.PostService.DeleteComment:input_type -> proto.DeleteCommentReq
	1,  // 11: proto.PostService.CreatePost:output_type -> proto.CreatePostResp
	2,  // 12: proto.PostService.GetPost:output_type -> proto.GetPostResp
	11, // 13: proto.PostService.DeletePost:output_type -> google.protobuf.Empty
	8,  // 14: proto.PostService.CheckLike:output_type -> proto.CheckLikeResp
	11, // 15: proto.PostService.AddLike:output_type -> google.protobuf.Empty
	11, // 16: proto.PostService.RemoveLike:output_type -> google.protobuf.Empty
	11, // 17: proto.PostService.AddComment:output_type -> google.protobuf.Empty
	11, // 18: proto.PostService.DeleteComment:output_type -> google.protobuf.Empty
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_post_grpc_proto_init() }
func file_post_grpc_proto_init() {
	if File_post_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_grpc_proto_rawDesc), len(file_post_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_grpc_proto_goTypes,
		DependencyIndexes: file_post_grpc_proto_depIdxs,
		MessageInfos:      file_post_grpc_proto_msgTypes,
	}.Build()
	File_post_grpc_proto = out.File
	file_post_grpc_proto_goTypes = nil
	file_post_grpc_proto_depIdxs = nil
}
