name: social-media-api
services:  
  api-gateway:
    image: coderbillzay/social-api-gateway
    # build: .
    container_name: api-gateway
    ports:
      - "${REST_PORT:-8000}:6950"
    depends_on:
      - authen-service
      - post-server
      - user-server
      - notification-server
      - chat-server
    environment:
      - APP_ENV=production
    networks:
      - app-network

  authen-service:
    image: coderbillzay/social-authen-service
    container_name: authen-service
    ports:
      - "${AUTH_PORT:-50051}:50051"
    networks:
      - app-network

  post-server:    
    image: coderbillzay/social-post-service
    container_name: post-service
    ports:
      - "${POST_PORT:-50052}:50052"
    networks:
      - app-network

  user-server:
    image: coderbillzay/social-user-service
    container_name: user-service
    ports:
      - "${USER_PORT:-50053}:50053"
    networks:
      - app-network

  notification-server:
    image: coderbillzay/social-notification-service
    container_name: notification-service
    ports:
      - "${NOTIFICATION_PORT:-50054}:50054"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_USERNAME=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASS:-guest}
    depends_on:
      - rabbitmq
    networks:
      - app-network

  chat-server:
    image: coderbillzay/social-chat-service
    container_name: chat-service
    ports:
      - "${CHAT_PORT:-50055}:50055"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_USERNAME=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASS:-guest}
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT:-15672}:15672"
    environment:
      - RABBITMQ_DEFAULT_USERNAME=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASSWORD=${RABBITMQ_PASS:-guest}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
