// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: notification-grpc.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationService_CreateSendNotify_FullMethodName = "/proto.NotificationService/CreateSendNotify"
	NotificationService_GetNotify_FullMethodName        = "/proto.NotificationService/GetNotify"
	NotificationService_GetUnreadNotify_FullMethodName  = "/proto.NotificationService/GetUnreadNotify"
	NotificationService_UpdateRead_FullMethodName       = "/proto.NotificationService/UpdateRead"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	CreateSendNotify(ctx context.Context, in *ReqSendNotify, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetNotify(ctx context.Context, in *ReqGetNotify, opts ...grpc.CallOption) (*RespNotificationsList, error)
	GetUnreadNotify(ctx context.Context, in *ReqUnreadList, opts ...grpc.CallOption) (*RespGetUnreadList, error)
	UpdateRead(ctx context.Context, in *ReqUpdateNotify, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) CreateSendNotify(ctx context.Context, in *ReqSendNotify, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotificationService_CreateSendNotify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetNotify(ctx context.Context, in *ReqGetNotify, opts ...grpc.CallOption) (*RespNotificationsList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespNotificationsList)
	err := c.cc.Invoke(ctx, NotificationService_GetNotify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetUnreadNotify(ctx context.Context, in *ReqUnreadList, opts ...grpc.CallOption) (*RespGetUnreadList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespGetUnreadList)
	err := c.cc.Invoke(ctx, NotificationService_GetUnreadNotify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) UpdateRead(ctx context.Context, in *ReqUpdateNotify, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotificationService_UpdateRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
type NotificationServiceServer interface {
	CreateSendNotify(context.Context, *ReqSendNotify) (*emptypb.Empty, error)
	GetNotify(context.Context, *ReqGetNotify) (*RespNotificationsList, error)
	GetUnreadNotify(context.Context, *ReqUnreadList) (*RespGetUnreadList, error)
	UpdateRead(context.Context, *ReqUpdateNotify) (*emptypb.Empty, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) CreateSendNotify(context.Context, *ReqSendNotify) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSendNotify not implemented")
}
func (UnimplementedNotificationServiceServer) GetNotify(context.Context, *ReqGetNotify) (*RespNotificationsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotify not implemented")
}
func (UnimplementedNotificationServiceServer) GetUnreadNotify(context.Context, *ReqUnreadList) (*RespGetUnreadList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnreadNotify not implemented")
}
func (UnimplementedNotificationServiceServer) UpdateRead(context.Context, *ReqUpdateNotify) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRead not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_CreateSendNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSendNotify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateSendNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateSendNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateSendNotify(ctx, req.(*ReqSendNotify))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetNotify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetNotify(ctx, req.(*ReqGetNotify))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetUnreadNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqUnreadList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetUnreadNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetUnreadNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetUnreadNotify(ctx, req.(*ReqUnreadList))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_UpdateRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqUpdateNotify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).UpdateRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_UpdateRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).UpdateRead(ctx, req.(*ReqUpdateNotify))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSendNotify",
			Handler:    _NotificationService_CreateSendNotify_Handler,
		},
		{
			MethodName: "GetNotify",
			Handler:    _NotificationService_GetNotify_Handler,
		},
		{
			MethodName: "GetUnreadNotify",
			Handler:    _NotificationService_GetUnreadNotify_Handler,
		},
		{
			MethodName: "UpdateRead",
			Handler:    _NotificationService_UpdateRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification-grpc.proto",
}
