// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// source: notification-grpc.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqUpdateNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotifyId string `protobuf:"bytes,1,opt,name=NotifyId,proto3" json:"NotifyId,omitempty"`
}

func (x *ReqUpdateNotify) Reset() {
	*x = ReqUpdateNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notification_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUpdateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUpdateNotify) ProtoMessage() {}

func (x *ReqUpdateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUpdateNotify.ProtoReflect.Descriptor instead.
func (*ReqUpdateNotify) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *ReqUpdateNotify) GetNotifyId() string {
	if x != nil {
		return x.NotifyId
	}
	return ""
}

type ReqGetNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverId string `protobuf:"bytes,1,opt,name=ReceiverId,proto3" json:"ReceiverId,omitempty"`
}

func (x *ReqGetNotify) Reset() {
	*x = ReqGetNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notification_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetNotify) ProtoMessage() {}

func (x *ReqGetNotify) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetNotify.ProtoReflect.Descriptor instead.
func (*ReqGetNotify) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *ReqGetNotify) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

type ReqUnreadList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *ReqUnreadList) Reset() {
	*x = ReqUnreadList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notification_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUnreadList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUnreadList) ProtoMessage() {}

func (x *ReqUnreadList) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUnreadList.ProtoReflect.Descriptor instead.
func (*ReqUnreadList) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *ReqUnreadList) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ReqSendNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderId   string `protobuf:"bytes,1,opt,name=SenderId,proto3" json:"SenderId,omitempty"`
	ReceiverId string `protobuf:"bytes,2,opt,name=ReceiverId,proto3" json:"ReceiverId,omitempty"`
	Messages   string `protobuf:"bytes,3,opt,name=Messages,proto3" json:"Messages,omitempty"`
	Type       string `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Url        string `protobuf:"bytes,5,opt,name=Url,proto3" json:"Url,omitempty"`
}

func (x *ReqSendNotify) Reset() {
	*x = ReqSendNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notification_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSendNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendNotify) ProtoMessage() {}

func (x *ReqSendNotify) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendNotify.ProtoReflect.Descriptor instead.
func (*ReqSendNotify) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *ReqSendNotify) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ReqSendNotify) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *ReqSendNotify) GetMessages() string {
	if x != nil {
		return x.Messages
	}
	return ""
}

func (x *ReqSendNotify) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReqSendNotify) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Notifications struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	SenderId   string                 `protobuf:"bytes,2,opt,name=SenderId,proto3" json:"SenderId,omitempty"`
	ReceiverId string                 `protobuf:"bytes,3,opt,name=ReceiverId,proto3" json:"ReceiverId,omitempty"`
	Messages   string                 `protobuf:"bytes,4,opt,name=Messages,proto3" json:"Messages,omitempty"`
	Type       string                 `protobuf:"bytes,5,opt,name=Type,proto3" json:"Type,omitempty"`
	Url        string                 `protobuf:"bytes,6,opt,name=Url,proto3" json:"Url,omitempty"`
	IsRead     bool                   `protobuf:"varint,7,opt,name=IsRead,proto3" json:"IsRead,omitempty"`
	Date       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=Date,proto3" json:"Date,omitempty"`
}

func (x *Notifications) Reset() {
	*x = Notifications{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notification_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notifications) ProtoMessage() {}

func (x *Notifications) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notifications.ProtoReflect.Descriptor instead.
func (*Notifications) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *Notifications) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notifications) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Notifications) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *Notifications) GetMessages() string {
	if x != nil {
		return x.Messages
	}
	return ""
}

func (x *Notifications) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notifications) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Notifications) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Notifications) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type RespNotificationsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Notifications []*Notifications `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
}

func (x *RespNotificationsList) Reset() {
	*x = RespNotificationsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notification_grpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespNotificationsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespNotificationsList) ProtoMessage() {}

func (x *RespNotificationsList) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespNotificationsList.ProtoReflect.Descriptor instead.
func (*RespNotificationsList) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *RespNotificationsList) GetNotifications() []*Notifications {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type RespGetUnreadList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *RespGetUnreadList) Reset() {
	*x = RespGetUnreadList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notification_grpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespGetUnreadList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespGetUnreadList) ProtoMessage() {}

func (x *RespGetUnreadList) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespGetUnreadList.ProtoReflect.Descriptor instead.
func (*RespGetUnreadList) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *RespGetUnreadList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_notification_grpc_proto protoreflect.FileDescriptor

var file_notification_grpc_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d,
	0x0a, 0x0f, 0x52, 0x65, 0x71, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x49, 0x64, 0x22, 0x2e, 0x0a,
	0x0c, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1e, 0x0a,
	0x0a, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x27, 0x0a,
	0x0d, 0x52, 0x65, 0x71, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x8d, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x53, 0x65,
	0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x22, 0xe5, 0x01, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x12, 0x2e,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x22, 0x53,
	0x0a, 0x15, 0x52, 0x65, 0x73, 0x70, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x29, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x47, 0x65, 0x74, 0x55, 0x6e,
	0x72, 0x65, 0x61, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x98,
	0x02, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x71, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55,
	0x6e, 0x72, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x47, 0x65,
	0x74, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0a, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x64, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x6c, 0x6c, 0x7a, 0x61, 0x79, 0x79,
	0x2f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x2d, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x62, 0x61,
	0x63, 0x6b, 0x2d, 0x65, 0x6e, 0x64, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notification_grpc_proto_rawDescOnce sync.Once
	file_notification_grpc_proto_rawDescData = file_notification_grpc_proto_rawDesc
)

func file_notification_grpc_proto_rawDescGZIP() []byte {
	file_notification_grpc_proto_rawDescOnce.Do(func() {
		file_notification_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_notification_grpc_proto_rawDescData)
	})
	return file_notification_grpc_proto_rawDescData
}

var file_notification_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_notification_grpc_proto_goTypes = []any{
	(*ReqUpdateNotify)(nil),       // 0: proto.ReqUpdateNotify
	(*ReqGetNotify)(nil),          // 1: proto.ReqGetNotify
	(*ReqUnreadList)(nil),         // 2: proto.ReqUnreadList
	(*ReqSendNotify)(nil),         // 3: proto.ReqSendNotify
	(*Notifications)(nil),         // 4: proto.Notifications
	(*RespNotificationsList)(nil), // 5: proto.RespNotificationsList
	(*RespGetUnreadList)(nil),     // 6: proto.RespGetUnreadList
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_notification_grpc_proto_depIdxs = []int32{
	7, // 0: proto.Notifications.Date:type_name -> google.protobuf.Timestamp
	4, // 1: proto.RespNotificationsList.notifications:type_name -> proto.Notifications
	3, // 2: proto.NotificationService.CreateSendNotify:input_type -> proto.ReqSendNotify
	1, // 3: proto.NotificationService.GetNotify:input_type -> proto.ReqGetNotify
	2, // 4: proto.NotificationService.GetUnreadNotify:input_type -> proto.ReqUnreadList
	0, // 5: proto.NotificationService.UpdateRead:input_type -> proto.ReqUpdateNotify
	8, // 6: proto.NotificationService.CreateSendNotify:output_type -> google.protobuf.Empty
	5, // 7: proto.NotificationService.GetNotify:output_type -> proto.RespNotificationsList
	6, // 8: proto.NotificationService.GetUnreadNotify:output_type -> proto.RespGetUnreadList
	8, // 9: proto.NotificationService.UpdateRead:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_notification_grpc_proto_init() }
func file_notification_grpc_proto_init() {
	if File_notification_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notification_grpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ReqUpdateNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notification_grpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ReqGetNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notification_grpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ReqUnreadList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notification_grpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ReqSendNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notification_grpc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Notifications); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notification_grpc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RespNotificationsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notification_grpc_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*RespGetUnreadList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notification_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_grpc_proto_goTypes,
		DependencyIndexes: file_notification_grpc_proto_depIdxs,
		MessageInfos:      file_notification_grpc_proto_msgTypes,
	}.Build()
	File_notification_grpc_proto = out.File
	file_notification_grpc_proto_rawDesc = nil
	file_notification_grpc_proto_goTypes = nil
	file_notification_grpc_proto_depIdxs = nil
}
