// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: notification-grpc.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqUpdateNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotifyId      string                 `protobuf:"bytes,1,opt,name=NotifyId,proto3" json:"NotifyId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUpdateNotify) Reset() {
	*x = ReqUpdateNotify{}
	mi := &file_notification_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUpdateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUpdateNotify) ProtoMessage() {}

func (x *ReqUpdateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUpdateNotify.ProtoReflect.Descriptor instead.
func (*ReqUpdateNotify) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *ReqUpdateNotify) GetNotifyId() string {
	if x != nil {
		return x.NotifyId
	}
	return ""
}

type ReqGetNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverId    string                 `protobuf:"bytes,1,opt,name=ReceiverId,proto3" json:"ReceiverId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetNotify) Reset() {
	*x = ReqGetNotify{}
	mi := &file_notification_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetNotify) ProtoMessage() {}

func (x *ReqGetNotify) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetNotify.ProtoReflect.Descriptor instead.
func (*ReqGetNotify) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *ReqGetNotify) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

type ReqUnreadList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUnreadList) Reset() {
	*x = ReqUnreadList{}
	mi := &file_notification_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUnreadList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUnreadList) ProtoMessage() {}

func (x *ReqUnreadList) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUnreadList.ProtoReflect.Descriptor instead.
func (*ReqUnreadList) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *ReqUnreadList) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ReqSendNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=SenderId,proto3" json:"SenderId,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,2,opt,name=ReceiverId,proto3" json:"ReceiverId,omitempty"`
	Messages      string                 `protobuf:"bytes,3,opt,name=Messages,proto3" json:"Messages,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=Url,proto3" json:"Url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqSendNotify) Reset() {
	*x = ReqSendNotify{}
	mi := &file_notification_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqSendNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendNotify) ProtoMessage() {}

func (x *ReqSendNotify) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendNotify.ProtoReflect.Descriptor instead.
func (*ReqSendNotify) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *ReqSendNotify) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ReqSendNotify) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *ReqSendNotify) GetMessages() string {
	if x != nil {
		return x.Messages
	}
	return ""
}

func (x *ReqSendNotify) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReqSendNotify) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Notifications struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=SenderId,proto3" json:"SenderId,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,3,opt,name=ReceiverId,proto3" json:"ReceiverId,omitempty"`
	Messages      string                 `protobuf:"bytes,4,opt,name=Messages,proto3" json:"Messages,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=Type,proto3" json:"Type,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=Url,proto3" json:"Url,omitempty"`
	IsRead        bool                   `protobuf:"varint,7,opt,name=IsRead,proto3" json:"IsRead,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=Date,proto3" json:"Date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notifications) Reset() {
	*x = Notifications{}
	mi := &file_notification_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notifications) ProtoMessage() {}

func (x *Notifications) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notifications.ProtoReflect.Descriptor instead.
func (*Notifications) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *Notifications) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notifications) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Notifications) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *Notifications) GetMessages() string {
	if x != nil {
		return x.Messages
	}
	return ""
}

func (x *Notifications) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notifications) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Notifications) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Notifications) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type RespNotificationsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notifications       `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespNotificationsList) Reset() {
	*x = RespNotificationsList{}
	mi := &file_notification_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespNotificationsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespNotificationsList) ProtoMessage() {}

func (x *RespNotificationsList) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespNotificationsList.ProtoReflect.Descriptor instead.
func (*RespNotificationsList) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *RespNotificationsList) GetNotifications() []*Notifications {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type RespGetUnreadList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespGetUnreadList) Reset() {
	*x = RespGetUnreadList{}
	mi := &file_notification_grpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespGetUnreadList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespGetUnreadList) ProtoMessage() {}

func (x *RespGetUnreadList) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespGetUnreadList.ProtoReflect.Descriptor instead.
func (*RespGetUnreadList) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *RespGetUnreadList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_notification_grpc_proto protoreflect.FileDescriptor

const file_notification_grpc_proto_rawDesc = "" +
	"\n" +
	"\x17notification-grpc.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"-\n" +
	"\x0fReqUpdateNotify\x12\x1a\n" +
	"\bNotifyId\x18\x01 \x01(\tR\bNotifyId\".\n" +
	"\fReqGetNotify\x12\x1e\n" +
	"\n" +
	"ReceiverId\x18\x01 \x01(\tR\n" +
	"ReceiverId\"'\n" +
	"\rReqUnreadList\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\"\x8d\x01\n" +
	"\rReqSendNotify\x12\x1a\n" +
	"\bSenderId\x18\x01 \x01(\tR\bSenderId\x12\x1e\n" +
	"\n" +
	"ReceiverId\x18\x02 \x01(\tR\n" +
	"ReceiverId\x12\x1a\n" +
	"\bMessages\x18\x03 \x01(\tR\bMessages\x12\x12\n" +
	"\x04Type\x18\x04 \x01(\tR\x04Type\x12\x10\n" +
	"\x03Url\x18\x05 \x01(\tR\x03Url\"\xe5\x01\n" +
	"\rNotifications\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x1a\n" +
	"\bSenderId\x18\x02 \x01(\tR\bSenderId\x12\x1e\n" +
	"\n" +
	"ReceiverId\x18\x03 \x01(\tR\n" +
	"ReceiverId\x12\x1a\n" +
	"\bMessages\x18\x04 \x01(\tR\bMessages\x12\x12\n" +
	"\x04Type\x18\x05 \x01(\tR\x04Type\x12\x10\n" +
	"\x03Url\x18\x06 \x01(\tR\x03Url\x12\x16\n" +
	"\x06IsRead\x18\a \x01(\bR\x06IsRead\x12.\n" +
	"\x04Date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x04Date\"S\n" +
	"\x15RespNotificationsList\x12:\n" +
	"\rnotifications\x18\x01 \x03(\v2\x14.proto.NotificationsR\rnotifications\")\n" +
	"\x11RespGetUnreadList\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2\x98\x02\n" +
	"\x13NotificationService\x12@\n" +
	"\x10CreateSendNotify\x12\x14.proto.ReqSendNotify\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\tGetNotify\x12\x13.proto.ReqGetNotify\x1a\x1c.proto.RespNotificationsList\x12A\n" +
	"\x0fGetUnreadNotify\x12\x14.proto.ReqUnreadList\x1a\x18.proto.RespGetUnreadList\x12<\n" +
	"\n" +
	"UpdateRead\x12\x16.proto.ReqUpdateNotify\x1a\x16.google.protobuf.EmptyBDZBgithub.com/billzayy/social-media/back-end/notification-service/apib\x06proto3"

var (
	file_notification_grpc_proto_rawDescOnce sync.Once
	file_notification_grpc_proto_rawDescData []byte
)

func file_notification_grpc_proto_rawDescGZIP() []byte {
	file_notification_grpc_proto_rawDescOnce.Do(func() {
		file_notification_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_grpc_proto_rawDesc), len(file_notification_grpc_proto_rawDesc)))
	})
	return file_notification_grpc_proto_rawDescData
}

var file_notification_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_notification_grpc_proto_goTypes = []any{
	(*ReqUpdateNotify)(nil),       // 0: proto.ReqUpdateNotify
	(*ReqGetNotify)(nil),          // 1: proto.ReqGetNotify
	(*ReqUnreadList)(nil),         // 2: proto.ReqUnreadList
	(*ReqSendNotify)(nil),         // 3: proto.ReqSendNotify
	(*Notifications)(nil),         // 4: proto.Notifications
	(*RespNotificationsList)(nil), // 5: proto.RespNotificationsList
	(*RespGetUnreadList)(nil),     // 6: proto.RespGetUnreadList
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_notification_grpc_proto_depIdxs = []int32{
	7, // 0: proto.Notifications.Date:type_name -> google.protobuf.Timestamp
	4, // 1: proto.RespNotificationsList.notifications:type_name -> proto.Notifications
	3, // 2: proto.NotificationService.CreateSendNotify:input_type -> proto.ReqSendNotify
	1, // 3: proto.NotificationService.GetNotify:input_type -> proto.ReqGetNotify
	2, // 4: proto.NotificationService.GetUnreadNotify:input_type -> proto.ReqUnreadList
	0, // 5: proto.NotificationService.UpdateRead:input_type -> proto.ReqUpdateNotify
	8, // 6: proto.NotificationService.CreateSendNotify:output_type -> google.protobuf.Empty
	5, // 7: proto.NotificationService.GetNotify:output_type -> proto.RespNotificationsList
	6, // 8: proto.NotificationService.GetUnreadNotify:output_type -> proto.RespGetUnreadList
	8, // 9: proto.NotificationService.UpdateRead:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_notification_grpc_proto_init() }
func file_notification_grpc_proto_init() {
	if File_notification_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_grpc_proto_rawDesc), len(file_notification_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_grpc_proto_goTypes,
		DependencyIndexes: file_notification_grpc_proto_depIdxs,
		MessageInfos:      file_notification_grpc_proto_msgTypes,
	}.Build()
	File_notification_grpc_proto = out.File
	file_notification_grpc_proto_goTypes = nil
	file_notification_grpc_proto_depIdxs = nil
}
