// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: user-grpc.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqGetUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetUser) Reset() {
	*x = ReqGetUser{}
	mi := &file_user_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetUser) ProtoMessage() {}

func (x *ReqGetUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetUser.ProtoReflect.Descriptor instead.
func (*ReqGetUser) Descriptor() ([]byte, []int) {
	return file_user_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *ReqGetUser) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type RespGetUser struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserName       string                 `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	FullName       string                 `protobuf:"bytes,3,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Email          string                 `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	UserSince      string                 `protobuf:"bytes,5,opt,name=UserSince,proto3" json:"UserSince,omitempty"`
	LastLogin      string                 `protobuf:"bytes,6,opt,name=LastLogin,proto3" json:"LastLogin,omitempty"`
	Active         bool                   `protobuf:"varint,7,opt,name=Active,proto3" json:"Active,omitempty"`
	ProfilePicture string                 `protobuf:"bytes,8,opt,name=ProfilePicture,proto3" json:"ProfilePicture,omitempty"`
	Description    string                 `protobuf:"bytes,9,opt,name=Description,proto3" json:"Description,omitempty"`
	Location       string                 `protobuf:"bytes,10,opt,name=Location,proto3" json:"Location,omitempty"`
	Website        []string               `protobuf:"bytes,11,rep,name=Website,proto3" json:"Website,omitempty"`
	BirthDate      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	Theme          string                 `protobuf:"bytes,13,opt,name=Theme,proto3" json:"Theme,omitempty"`
	Language       string                 `protobuf:"bytes,14,opt,name=Language,proto3" json:"Language,omitempty"`
	Country        string                 `protobuf:"bytes,15,opt,name=Country,proto3" json:"Country,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RespGetUser) Reset() {
	*x = RespGetUser{}
	mi := &file_user_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespGetUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespGetUser) ProtoMessage() {}

func (x *RespGetUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespGetUser.ProtoReflect.Descriptor instead.
func (*RespGetUser) Descriptor() ([]byte, []int) {
	return file_user_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *RespGetUser) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RespGetUser) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RespGetUser) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RespGetUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RespGetUser) GetUserSince() string {
	if x != nil {
		return x.UserSince
	}
	return ""
}

func (x *RespGetUser) GetLastLogin() string {
	if x != nil {
		return x.LastLogin
	}
	return ""
}

func (x *RespGetUser) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *RespGetUser) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

func (x *RespGetUser) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RespGetUser) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RespGetUser) GetWebsite() []string {
	if x != nil {
		return x.Website
	}
	return nil
}

func (x *RespGetUser) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *RespGetUser) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *RespGetUser) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *RespGetUser) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type ReqUpdateInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserName       string                 `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	FullName       string                 `protobuf:"bytes,3,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Email          string                 `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	ProfilePicture string                 `protobuf:"bytes,5,opt,name=ProfilePicture,proto3" json:"ProfilePicture,omitempty"`
	Description    string                 `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`
	Location       string                 `protobuf:"bytes,7,opt,name=Location,proto3" json:"Location,omitempty"`
	Website        []string               `protobuf:"bytes,8,rep,name=Website,proto3" json:"Website,omitempty"`
	BirthDate      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	Theme          string                 `protobuf:"bytes,10,opt,name=Theme,proto3" json:"Theme,omitempty"`
	Language       string                 `protobuf:"bytes,11,opt,name=Language,proto3" json:"Language,omitempty"`
	Country        string                 `protobuf:"bytes,12,opt,name=Country,proto3" json:"Country,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReqUpdateInfo) Reset() {
	*x = ReqUpdateInfo{}
	mi := &file_user_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUpdateInfo) ProtoMessage() {}

func (x *ReqUpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUpdateInfo.ProtoReflect.Descriptor instead.
func (*ReqUpdateInfo) Descriptor() ([]byte, []int) {
	return file_user_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *ReqUpdateInfo) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ReqUpdateInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ReqUpdateInfo) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *ReqUpdateInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReqUpdateInfo) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

func (x *ReqUpdateInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReqUpdateInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ReqUpdateInfo) GetWebsite() []string {
	if x != nil {
		return x.Website
	}
	return nil
}

func (x *ReqUpdateInfo) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *ReqUpdateInfo) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *ReqUpdateInfo) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ReqUpdateInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type ReqUpdatePassword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=OldPassword,proto3" json:"OldPassword,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUpdatePassword) Reset() {
	*x = ReqUpdatePassword{}
	mi := &file_user_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUpdatePassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUpdatePassword) ProtoMessage() {}

func (x *ReqUpdatePassword) ProtoReflect() protoreflect.Message {
	mi := &file_user_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUpdatePassword.ProtoReflect.Descriptor instead.
func (*ReqUpdatePassword) Descriptor() ([]byte, []int) {
	return file_user_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *ReqUpdatePassword) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ReqUpdatePassword) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ReqUpdatePassword) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

var File_user_grpc_proto protoreflect.FileDescriptor

const file_user_grpc_proto_rawDesc = "" +
	"\n" +
	"\x0fuser-grpc.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1c\n" +
	"\n" +
	"ReqGetUser\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"\xc5\x03\n" +
	"\vRespGetUser\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bUserName\x18\x02 \x01(\tR\bUserName\x12\x1a\n" +
	"\bFullName\x18\x03 \x01(\tR\bFullName\x12\x14\n" +
	"\x05Email\x18\x04 \x01(\tR\x05Email\x12\x1c\n" +
	"\tUserSince\x18\x05 \x01(\tR\tUserSince\x12\x1c\n" +
	"\tLastLogin\x18\x06 \x01(\tR\tLastLogin\x12\x16\n" +
	"\x06Active\x18\a \x01(\bR\x06Active\x12&\n" +
	"\x0eProfilePicture\x18\b \x01(\tR\x0eProfilePicture\x12 \n" +
	"\vDescription\x18\t \x01(\tR\vDescription\x12\x1a\n" +
	"\bLocation\x18\n" +
	" \x01(\tR\bLocation\x12\x18\n" +
	"\aWebsite\x18\v \x03(\tR\aWebsite\x128\n" +
	"\tBirthDate\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tBirthDate\x12\x14\n" +
	"\x05Theme\x18\r \x01(\tR\x05Theme\x12\x1a\n" +
	"\bLanguage\x18\x0e \x01(\tR\bLanguage\x12\x18\n" +
	"\aCountry\x18\x0f \x01(\tR\aCountry\"\xf3\x02\n" +
	"\rReqUpdateInfo\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bUserName\x18\x02 \x01(\tR\bUserName\x12\x1a\n" +
	"\bFullName\x18\x03 \x01(\tR\bFullName\x12\x14\n" +
	"\x05Email\x18\x04 \x01(\tR\x05Email\x12&\n" +
	"\x0eProfilePicture\x18\x05 \x01(\tR\x0eProfilePicture\x12 \n" +
	"\vDescription\x18\x06 \x01(\tR\vDescription\x12\x1a\n" +
	"\bLocation\x18\a \x01(\tR\bLocation\x12\x18\n" +
	"\aWebsite\x18\b \x03(\tR\aWebsite\x128\n" +
	"\tBirthDate\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tBirthDate\x12\x14\n" +
	"\x05Theme\x18\n" +
	" \x01(\tR\x05Theme\x12\x1a\n" +
	"\bLanguage\x18\v \x01(\tR\bLanguage\x12\x18\n" +
	"\aCountry\x18\f \x01(\tR\aCountry\"g\n" +
	"\x11ReqUpdatePassword\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12 \n" +
	"\vOldPassword\x18\x02 \x01(\tR\vOldPassword\x12 \n" +
	"\vNewPassword\x18\x03 \x01(\tR\vNewPassword2\xc7\x01\n" +
	"\vUserService\x124\n" +
	"\vGetUserById\x12\x11.proto.ReqGetUser\x1a\x12.proto.RespGetUser\x12>\n" +
	"\x0eUpdateInfoUser\x12\x14.proto.ReqUpdateInfo\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x0eUpdatePassword\x12\x18.proto.ReqUpdatePassword\x1a\x16.google.protobuf.EmptyB<Z:github.com/billzayy/social-media/back-end/user-service/apib\x06proto3"

var (
	file_user_grpc_proto_rawDescOnce sync.Once
	file_user_grpc_proto_rawDescData []byte
)

func file_user_grpc_proto_rawDescGZIP() []byte {
	file_user_grpc_proto_rawDescOnce.Do(func() {
		file_user_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_grpc_proto_rawDesc), len(file_user_grpc_proto_rawDesc)))
	})
	return file_user_grpc_proto_rawDescData
}

var file_user_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_grpc_proto_goTypes = []any{
	(*ReqGetUser)(nil),            // 0: proto.ReqGetUser
	(*RespGetUser)(nil),           // 1: proto.RespGetUser
	(*ReqUpdateInfo)(nil),         // 2: proto.ReqUpdateInfo
	(*ReqUpdatePassword)(nil),     // 3: proto.ReqUpdatePassword
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_user_grpc_proto_depIdxs = []int32{
	4, // 0: proto.RespGetUser.BirthDate:type_name -> google.protobuf.Timestamp
	4, // 1: proto.ReqUpdateInfo.BirthDate:type_name -> google.protobuf.Timestamp
	0, // 2: proto.UserService.GetUserById:input_type -> proto.ReqGetUser
	2, // 3: proto.UserService.UpdateInfoUser:input_type -> proto.ReqUpdateInfo
	3, // 4: proto.UserService.UpdatePassword:input_type -> proto.ReqUpdatePassword
	1, // 5: proto.UserService.GetUserById:output_type -> proto.RespGetUser
	5, // 6: proto.UserService.UpdateInfoUser:output_type -> google.protobuf.Empty
	5, // 7: proto.UserService.UpdatePassword:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_grpc_proto_init() }
func file_user_grpc_proto_init() {
	if File_user_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_grpc_proto_rawDesc), len(file_user_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_grpc_proto_goTypes,
		DependencyIndexes: file_user_grpc_proto_depIdxs,
		MessageInfos:      file_user_grpc_proto_msgTypes,
	}.Build()
	File_user_grpc_proto = out.File
	file_user_grpc_proto_goTypes = nil
	file_user_grpc_proto_depIdxs = nil
}
