// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: chat-grpc.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqSendPrivateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=SenderId,proto3" json:"SenderId,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,2,opt,name=ReceiverId,proto3" json:"ReceiverId,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	MessageType   string                 `protobuf:"bytes,4,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqSendPrivateMessage) Reset() {
	*x = ReqSendPrivateMessage{}
	mi := &file_chat_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqSendPrivateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendPrivateMessage) ProtoMessage() {}

func (x *ReqSendPrivateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendPrivateMessage.ProtoReflect.Descriptor instead.
func (*ReqSendPrivateMessage) Descriptor() ([]byte, []int) {
	return file_chat_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *ReqSendPrivateMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ReqSendPrivateMessage) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *ReqSendPrivateMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReqSendPrivateMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

type RespSendPrivateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespSendPrivateMessage) Reset() {
	*x = RespSendPrivateMessage{}
	mi := &file_chat_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespSendPrivateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespSendPrivateMessage) ProtoMessage() {}

func (x *RespSendPrivateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespSendPrivateMessage.ProtoReflect.Descriptor instead.
func (*RespSendPrivateMessage) Descriptor() ([]byte, []int) {
	return file_chat_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *RespSendPrivateMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type ReqGetMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=ConversationId,proto3" json:"ConversationId,omitempty"`
	Limit          int64                  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset         int64                  `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReqGetMessage) Reset() {
	*x = ReqGetMessage{}
	mi := &file_chat_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetMessage) ProtoMessage() {}

func (x *ReqGetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetMessage.ProtoReflect.Descriptor instead.
func (*ReqGetMessage) Descriptor() ([]byte, []int) {
	return file_chat_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *ReqGetMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ReqGetMessage) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ReqGetMessage) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type RespListMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*RespGetMessage      `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespListMessage) Reset() {
	*x = RespListMessage{}
	mi := &file_chat_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespListMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespListMessage) ProtoMessage() {}

func (x *RespListMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespListMessage.ProtoReflect.Descriptor instead.
func (*RespListMessage) Descriptor() ([]byte, []int) {
	return file_chat_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *RespListMessage) GetData() []*RespGetMessage {
	if x != nil {
		return x.Data
	}
	return nil
}

type RespGetMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Sender        *User                  `protobuf:"bytes,2,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	MessageType   string                 `protobuf:"bytes,4,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespGetMessage) Reset() {
	*x = RespGetMessage{}
	mi := &file_chat_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespGetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespGetMessage) ProtoMessage() {}

func (x *RespGetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespGetMessage.ProtoReflect.Descriptor instead.
func (*RespGetMessage) Descriptor() ([]byte, []int) {
	return file_chat_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *RespGetMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RespGetMessage) GetSender() *User {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *RespGetMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RespGetMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *RespGetMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ReqDeleteMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqDeleteMessage) Reset() {
	*x = ReqDeleteMessage{}
	mi := &file_chat_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqDeleteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDeleteMessage) ProtoMessage() {}

func (x *ReqDeleteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqDeleteMessage.ProtoReflect.Descriptor instead.
func (*ReqDeleteMessage) Descriptor() ([]byte, []int) {
	return file_chat_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *ReqDeleteMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_chat_grpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_chat_grpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_chat_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

var File_chat_grpc_proto protoreflect.FileDescriptor

const file_chat_grpc_proto_rawDesc = "" +
	"\n" +
	"\x0fchat-grpc.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\x8f\x01\n" +
	"\x15ReqSendPrivateMessage\x12\x1a\n" +
	"\bSenderId\x18\x01 \x01(\tR\bSenderId\x12\x1e\n" +
	"\n" +
	"ReceiverId\x18\x02 \x01(\tR\n" +
	"ReceiverId\x12\x18\n" +
	"\aContent\x18\x03 \x01(\tR\aContent\x12 \n" +
	"\vMessageType\x18\x04 \x01(\tR\vMessageType\"0\n" +
	"\x16RespSendPrivateMessage\x12\x16\n" +
	"\x06RoomId\x18\x01 \x01(\tR\x06RoomId\"e\n" +
	"\rReqGetMessage\x12&\n" +
	"\x0eConversationId\x18\x01 \x01(\tR\x0eConversationId\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\x03R\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x03 \x01(\x03R\x06Offset\"<\n" +
	"\x0fRespListMessage\x12)\n" +
	"\x04Data\x18\x01 \x03(\v2\x15.proto.RespGetMessageR\x04Data\"\x9f\x01\n" +
	"\x0eRespGetMessage\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12#\n" +
	"\x06Sender\x18\x02 \x01(\v2\v.proto.UserR\x06Sender\x12\x18\n" +
	"\aContent\x18\x03 \x01(\tR\aContent\x12 \n" +
	"\vMessageType\x18\x04 \x01(\tR\vMessageType\x12\x1c\n" +
	"\tCreatedAt\x18\x05 \x01(\tR\tCreatedAt\"0\n" +
	"\x10ReqDeleteMessage\x12\x1c\n" +
	"\tMessageId\x18\x01 \x01(\tR\tMessageId\"R\n" +
	"\x04User\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x1a\n" +
	"\bUserName\x18\x02 \x01(\tR\bUserName\x12\x16\n" +
	"\x06Avatar\x18\x03 \x01(\tR\x06Avatar2\xe3\x01\n" +
	"\vChatService\x12:\n" +
	"\n" +
	"GetMessage\x12\x14.proto.ReqGetMessage\x1a\x16.proto.RespListMessage\x12V\n" +
	"\x17SendPrivateConversation\x12\x1c.proto.ReqSendPrivateMessage\x1a\x1d.proto.RespSendPrivateMessage\x12@\n" +
	"\rDeleteMessage\x12\x17.proto.ReqDeleteMessage\x1a\x16.google.protobuf.EmptyB<Z:github.com/billzayy/social-media/back-end/chat-service/apib\x06proto3"

var (
	file_chat_grpc_proto_rawDescOnce sync.Once
	file_chat_grpc_proto_rawDescData []byte
)

func file_chat_grpc_proto_rawDescGZIP() []byte {
	file_chat_grpc_proto_rawDescOnce.Do(func() {
		file_chat_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_grpc_proto_rawDesc), len(file_chat_grpc_proto_rawDesc)))
	})
	return file_chat_grpc_proto_rawDescData
}

var file_chat_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_chat_grpc_proto_goTypes = []any{
	(*ReqSendPrivateMessage)(nil),  // 0: proto.ReqSendPrivateMessage
	(*RespSendPrivateMessage)(nil), // 1: proto.RespSendPrivateMessage
	(*ReqGetMessage)(nil),          // 2: proto.ReqGetMessage
	(*RespListMessage)(nil),        // 3: proto.RespListMessage
	(*RespGetMessage)(nil),         // 4: proto.RespGetMessage
	(*ReqDeleteMessage)(nil),       // 5: proto.ReqDeleteMessage
	(*User)(nil),                   // 6: proto.User
	(*emptypb.Empty)(nil),          // 7: google.protobuf.Empty
}
var file_chat_grpc_proto_depIdxs = []int32{
	4, // 0: proto.RespListMessage.Data:type_name -> proto.RespGetMessage
	6, // 1: proto.RespGetMessage.Sender:type_name -> proto.User
	2, // 2: proto.ChatService.GetMessage:input_type -> proto.ReqGetMessage
	0, // 3: proto.ChatService.SendPrivateConversation:input_type -> proto.ReqSendPrivateMessage
	5, // 4: proto.ChatService.DeleteMessage:input_type -> proto.ReqDeleteMessage
	3, // 5: proto.ChatService.GetMessage:output_type -> proto.RespListMessage
	1, // 6: proto.ChatService.SendPrivateConversation:output_type -> proto.RespSendPrivateMessage
	7, // 7: proto.ChatService.DeleteMessage:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chat_grpc_proto_init() }
func file_chat_grpc_proto_init() {
	if File_chat_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_grpc_proto_rawDesc), len(file_chat_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_grpc_proto_goTypes,
		DependencyIndexes: file_chat_grpc_proto_depIdxs,
		MessageInfos:      file_chat_grpc_proto_msgTypes,
	}.Build()
	File_chat_grpc_proto = out.File
	file_chat_grpc_proto_goTypes = nil
	file_chat_grpc_proto_depIdxs = nil
}
